# This is a basic workflow to help you get started with Actions

name: Task Census

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
      
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Create manifest.yml
      run: |
        export compCount=$( grep -L "//dev" **/*.cpp | wc -l )
        export compList=$( grep -L "//dev" **/*.cpp | sed 's/.cpp.*//;s/^/    /' )
        export attempted=$( grep "//dev" **/*.cpp | wc -l )
        export incompList=$( grep "//dev" **/*.cpp | sed 's/.cpp.*//;s/^/    /' )
        export nl=$'\n'
        export in=$'  '
        cat <<EOF > ./manifest.yml
        # Online Judge Storage Status
        # repo: tanxpyox/oj
        # Author:
        #   - tanxpyox <tanxpyox@gmail.com>
        # License: AGPLv3 <https://github.com/tanxpyox/oj/blob/master/LICENSE>
        # Last Update: $(TZ=Asia/Hong_Kong date '+%Y-%m-%d %H:%M:%S')
        
        completed: 
          count: $compCount
          tasks: |
        $compList
        
        under-development: 
          count: $attempted
          tasks: |
        $incompList
        EOF
        
    - name: Validate
      run: cat ./manifest.yml
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: manifest.yml
        # A file, directory or wildcard pattern that describes what to upload
        path: ./manifest.yml
 
